// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWa7EaZroLELQSj1HoMuaHmPcsrcsSms',
    appId: '1:264341710340:web:d0113162f7b7ff37f4b751',
    messagingSenderId: '264341710340',
    projectId: 'recipe-test-5a543',
    authDomain: 'recipe-test-5a543.firebaseapp.com',
    storageBucket: 'recipe-test-5a543.appspot.com',
    measurementId: 'G-YCZ3JZ3937',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtKJWGxhGnMzsb4f-GG6135DoZXc1IddA',
    appId: '1:264341710340:android:05e790fc7033cd7af4b751',
    messagingSenderId: '264341710340',
    projectId: 'recipe-test-5a543',
    storageBucket: 'recipe-test-5a543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtrgjlS_ZwM3uTUhH0bI1Ot0OwbVVQ9wY',
    appId: '1:264341710340:ios:eb8b2f34f23de58bf4b751',
    messagingSenderId: '264341710340',
    projectId: 'recipe-test-5a543',
    storageBucket: 'recipe-test-5a543.appspot.com',
    iosClientId: '264341710340-tk27huhpvke58umnlhcb59bb2i341ggu.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtrgjlS_ZwM3uTUhH0bI1Ot0OwbVVQ9wY',
    appId: '1:264341710340:ios:eb8b2f34f23de58bf4b751',
    messagingSenderId: '264341710340',
    projectId: 'recipe-test-5a543',
    storageBucket: 'recipe-test-5a543.appspot.com',
    iosClientId: '264341710340-tk27huhpvke58umnlhcb59bb2i341ggu.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeTest',
  );
}
